---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - name: syslog
      syslog:
        rfc: RFC5424
        url: 'udp://collector.openshift-logging.svc:514'
        appName: logs
      type: syslog
  pipelines:
    - inputRefs:
        - application
      name: logs-to-syslog
      outputRefs:
        - syslog
  serviceAccount:
    name: kleio
